### ISSUE TITLE
Delete note after adding a new one

### ISSUE THREAD

**Issue by abahmed** [abahmed/Deer#134]
**Describe the bug**
After adding a new note and trying to delete the new note, it fails.

**To Reproduce**
1. Click on New Note button
2. After a new note is added, click on Delete button
4. Status message shows that note cannot be deleted

**Expected behavior**
Note should be deleted.

**Comment by jesusbibieca** [comment]
Hey! I'm new to programming, but I'd like to try to fix this.

**Comment by jesusbibieca** [comment]
This seems to be happening because the note is not in the db and it's trying to delete a doc that doesn't exist. 
https://github.com/abahmed/Deer/blob/develop/app/actions/note.js#L100

Possible solution (What I'm working on right now): making sure that the note exists before you try to delete it and if it doesn't, warn the user that the note needs to be saved first in order to delete it.

**Comment by abahmed** [comment]
Hello @jesusbibieca 
You are welcome to work on this issue. Don’t worry if you’re new, we are here to help you. You can read Our Docs, join us on [Gitter](https://gitter.im/abahmed/Deer) to ask, inquire about anything you need to know, or get helped.

Your solution is good, but I think we can something better e.g use flag to indicate that to avoid asynchronous calls to detect that and disable the button if it’s not needed. What do you think?

**Comment by enzo-beltrami** [comment]
I think we should persist the empty note in the db because I think this problem is linked to #135
