### ISSUE TITLE
delete button deletes all notes not selected note

### ISSUE THREAD

**Issue by nwyll** [abahmed/Deer#137]
Describe the bug:
When you create multiple notes then select one to be deleted all notes are deleted.

Firstly, Add and save a new note
Add another new note, add some text and save the note
Select one of the notes 
Click delete and say yes in the modal

Expected behavior:
I would expect only the selected note to be deleted not all notes.

**Comment by enzo-beltrami** [comment]
Is someone working at this? i would love to start contributing here... It seems to be an Logic error at both Note action and Reducer

note action Line 102 :
`dispatch(deleteNoteFromList(noteIndex)) //Should be result.id instead of noteIndex`

note reducer Line 98:
`notes: state.notes.filter(note => note.id === action.payload) //Should be !== instead of ===`

**Comment by abahmed** [comment]
Thanks for working on this Enzo 👍. You’re right about errors and the fix.
Thanks @nwyll and @enzo-beltrami for contributing to Deer and we wish to continue contributing.
