### ISSUE TITLE
Improve note object

### ISSUE THREAD

**Issue by jesusbibieca** [abahmed/Deer#156]
**Is your feature request related to a problem? Please describe.**
Right now we are catching if a note is not saved in the db and repeating logic over and over.

Reference to https://github.com/abahmed/Deer/blob/develop/app/actions/note.js#L95

**Describe the solution you'd like**
My solution would be to add a `isNoteSaved` property to the note object to be able to just ask if the note is saved fetch data from the db otherwise do not fetch data from the db.

**Describe alternatives you've considered**

**Additional context**

**Comment by jesusbibieca** [comment]
If you guys are ok with this I want to make this change. @abahmed

**Comment by abahmed** [comment]
:+1: you need to be careful about isNoteSaved, it means "it exists in db, but not saved, so just update is needed" or "it does not exist in db, so it needs to be saved".

**Comment by jesusbibieca** [comment]
You're right about this... Will hold on for now since it might relate to #136 as well.

**Comment by abahmed** [comment]
Current code has been changed, but note object needs to be improved in another way and this is a list of proposed work
- Support Immutable js
- note list (for viewing) will only contain IDs 
- Support 2 level lookup for note through caching fetched notes instead of fetching them every time from database
- use 3 status for note (READY, LOADING, and FAIL)

This is a list of expected work to improve notes in general
